### PR TITLE
save additional fields in mailchimp

### PR DESCRIPTION
**Pull request by littleq0903**

### CODE REVIEW

**Comment by natea** [comment]
The add_email_to_mailchimp_list function is missing tests.

screen shot 2013-08-13 at 3 02 30 pm

**Comment by bezidejni** [comment]
I don't think that Colin can test that since it's a call to an external service. He can try mocking it but we wouldn't really gain much by having that test.

**Comment by natea** [comment]
@bezidejni doesn't ms.listSubscribe have a return value? True if it's successful or False if it's not? We're returning True no matter what happens with that ms.listSubscribe call.

Ideally, this should probably be background executed using Celery so that the user registration doesn't fail if Mailchimp is down for some reason, or if our server can't talk to the Mailchimp servers.

**Comment by natea** [comment]
@littleq0903 have you written tests for this new Mailchimp functionality yet?

**Pull request merged**
